
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package golite.parser;

import java_cup.runtime.*;
import golite.ast.*;
import java.util.ArrayList;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\110\000\002\002\004\000\002\002\003\000\002\025" +
    "\004\000\002\025\003\000\002\025\002\000\002\004\005" +
    "\000\002\003\003\000\002\003\003\000\002\003\003\000" +
    "\002\003\003\000\002\003\003\000\002\003\003\000\002" +
    "\003\003\000\002\003\004\000\002\003\003\000\002\003" +
    "\004\000\002\003\004\000\002\005\007\000\002\005\005" +
    "\000\002\005\005\000\002\006\005\000\002\006\005\000" +
    "\002\006\005\000\002\024\003\000\002\024\003\000\002" +
    "\024\003\000\002\024\003\000\002\024\003\000\002\007" +
    "\005\000\002\007\007\000\002\010\005\000\002\022\007" +
    "\000\002\022\006\000\002\023\006\000\002\023\006\000" +
    "\002\023\006\000\002\026\005\000\002\026\003\000\002" +
    "\026\002\000\002\011\003\000\002\012\005\000\002\012" +
    "\003\000\002\013\005\000\002\013\003\000\002\014\005" +
    "\000\002\014\005\000\002\014\003\000\002\015\005\000" +
    "\002\015\005\000\002\015\005\000\002\015\005\000\002" +
    "\015\003\000\002\016\005\000\002\016\005\000\002\016" +
    "\003\000\002\017\005\000\002\017\005\000\002\017\005" +
    "\000\002\017\003\000\002\020\004\000\002\020\004\000" +
    "\002\020\003\000\002\021\003\000\002\021\003\000\002" +
    "\021\003\000\002\021\003\000\002\021\003\000\002\021" +
    "\003\000\002\021\003\000\002\021\003\000\002\021\005" +
    "\000\002\021\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\166\000\032\002\ufffd\004\030\005\010\007\026\010" +
    "\024\011\004\022\022\023\016\024\027\025\020\054\015" +
    "\061\013\001\002\000\034\002\ufff6\004\ufff6\005\ufff6\007" +
    "\ufff6\010\ufff6\011\ufff6\022\ufff6\023\ufff6\024\ufff6\025\ufff6" +
    "\054\ufff6\055\ufff6\061\ufff6\001\002\000\032\002\000\004" +
    "\030\005\010\007\026\010\024\011\004\022\022\023\016" +
    "\024\027\025\020\054\015\061\013\001\002\000\034\002" +
    "\ufff9\004\ufff9\005\ufff9\007\ufff9\010\ufff9\011\ufff9\022\ufff9" +
    "\023\ufff9\024\ufff9\025\ufff9\054\ufff9\055\ufff9\061\ufff9\001" +
    "\002\000\034\002\ufff3\004\ufff3\005\ufff3\007\ufff3\010\ufff3" +
    "\011\ufff3\022\ufff3\023\ufff3\024\ufff3\025\ufff3\054\ufff3\055" +
    "\ufff3\061\ufff3\001\002\000\036\012\052\013\063\014\053" +
    "\023\016\024\027\025\020\027\042\051\046\052\050\061" +
    "\054\062\060\063\057\065\065\066\056\001\002\000\034" +
    "\002\ufff5\004\ufff5\005\ufff5\007\ufff5\010\ufff5\011\ufff5\022" +
    "\ufff5\023\ufff5\024\ufff5\025\ufff5\054\ufff5\055\ufff5\061\ufff5" +
    "\001\002\000\034\002\ufffa\004\ufffa\005\ufffa\007\ufffa\010" +
    "\ufffa\011\ufffa\022\ufffa\023\ufffa\024\ufffa\025\ufffa\054\ufffa" +
    "\055\ufffa\061\ufffa\001\002\000\016\033\157\034\155\035" +
    "\153\036\160\037\156\040\154\001\002\000\004\002\152" +
    "\001\002\000\032\004\030\005\010\007\026\010\024\011" +
    "\004\022\022\023\016\024\027\025\020\054\015\055\ufffd" +
    "\061\013\001\002\000\004\052\144\001\002\000\034\002" +
    "\ufffe\004\ufffe\005\ufffe\007\ufffe\010\ufffe\011\ufffe\022\ufffe" +
    "\023\ufffe\024\ufffe\025\ufffe\054\ufffe\055\ufffe\061\ufffe\001" +
    "\002\000\004\052\141\001\002\000\034\002\ufff8\004\ufff8" +
    "\005\ufff8\007\ufff8\010\ufff8\011\ufff8\022\ufff8\023\ufff8\024" +
    "\ufff8\025\ufff8\054\ufff8\055\ufff8\061\ufff8\001\002\000\004" +
    "\052\132\001\002\000\004\057\131\001\002\000\034\002" +
    "\ufff7\004\ufff7\005\ufff7\007\ufff7\010\ufff7\011\ufff7\022\ufff7" +
    "\023\ufff7\024\ufff7\025\ufff7\054\ufff7\055\ufff7\061\ufff7\001" +
    "\002\000\034\002\ufffb\004\ufffb\005\ufffb\007\ufffb\010\ufffb" +
    "\011\ufffb\022\ufffb\023\ufffb\024\ufffb\025\ufffb\054\ufffb\055" +
    "\ufffb\061\ufffb\001\002\000\036\012\052\013\063\014\053" +
    "\023\016\024\027\025\020\027\042\051\046\052\050\061" +
    "\054\062\060\063\057\065\065\066\056\001\002\000\004" +
    "\052\124\001\002\000\004\061\031\001\002\000\014\015" +
    "\032\016\034\017\037\020\036\021\035\001\002\000\036" +
    "\002\uffea\004\uffea\005\uffea\007\uffea\010\uffea\011\uffea\022" +
    "\uffea\023\uffea\024\uffea\025\uffea\033\uffea\054\uffea\055\uffea" +
    "\061\uffea\001\002\000\036\002\uffef\004\uffef\005\uffef\007" +
    "\uffef\010\uffef\011\uffef\022\uffef\023\uffef\024\uffef\025\uffef" +
    "\033\040\054\uffef\055\uffef\061\uffef\001\002\000\036\002" +
    "\uffe9\004\uffe9\005\uffe9\007\uffe9\010\uffe9\011\uffe9\022\uffe9" +
    "\023\uffe9\024\uffe9\025\uffe9\033\uffe9\054\uffe9\055\uffe9\061" +
    "\uffe9\001\002\000\036\002\uffe6\004\uffe6\005\uffe6\007\uffe6" +
    "\010\uffe6\011\uffe6\022\uffe6\023\uffe6\024\uffe6\025\uffe6\033" +
    "\uffe6\054\uffe6\055\uffe6\061\uffe6\001\002\000\036\002\uffe7" +
    "\004\uffe7\005\uffe7\007\uffe7\010\uffe7\011\uffe7\022\uffe7\023" +
    "\uffe7\024\uffe7\025\uffe7\033\uffe7\054\uffe7\055\uffe7\061\uffe7" +
    "\001\002\000\036\002\uffe8\004\uffe8\005\uffe8\007\uffe8\010" +
    "\uffe8\011\uffe8\022\uffe8\023\uffe8\024\uffe8\025\uffe8\033\uffe8" +
    "\054\uffe8\055\uffe8\061\uffe8\001\002\000\036\012\052\013" +
    "\063\014\053\023\016\024\027\025\020\027\042\051\046" +
    "\052\050\061\054\062\060\063\057\065\065\066\056\001" +
    "\002\000\064\002\uffce\004\uffce\005\uffce\007\uffce\010\uffce" +
    "\011\uffce\022\uffce\023\uffce\024\uffce\025\uffce\026\076\027" +
    "\077\041\uffce\042\uffce\043\uffce\044\uffce\045\uffce\046\uffce" +
    "\047\uffce\050\uffce\053\uffce\054\uffce\055\uffce\056\uffce\061" +
    "\uffce\001\002\000\036\012\052\013\063\014\053\023\016" +
    "\024\027\025\020\027\042\051\046\052\050\061\054\062" +
    "\060\063\057\065\065\066\056\001\002\000\042\002\uffda" +
    "\004\uffda\005\uffda\007\uffda\010\uffda\011\uffda\022\uffda\023" +
    "\uffda\024\uffda\025\uffda\050\121\053\uffda\054\uffda\055\uffda" +
    "\056\uffda\061\uffda\001\002\000\034\002\ufff0\004\ufff0\005" +
    "\ufff0\007\ufff0\010\ufff0\011\ufff0\022\ufff0\023\ufff0\024\ufff0" +
    "\025\ufff0\054\ufff0\055\ufff0\061\ufff0\001\002\000\072\002" +
    "\uffc4\004\uffc4\005\uffc4\007\uffc4\010\uffc4\011\uffc4\022\uffc4" +
    "\023\uffc4\024\uffc4\025\uffc4\026\uffc4\027\uffc4\030\uffc4\031" +
    "\uffc4\032\uffc4\041\uffc4\042\uffc4\043\uffc4\044\uffc4\045\uffc4" +
    "\046\uffc4\047\uffc4\050\uffc4\053\uffc4\054\uffc4\055\uffc4\056" +
    "\uffc4\061\uffc4\001\002\000\036\012\052\013\063\014\053" +
    "\023\016\024\027\025\020\027\042\051\046\052\050\061" +
    "\054\062\060\063\057\065\065\066\056\001\002\000\072" +
    "\002\uffc7\004\uffc7\005\uffc7\007\uffc7\010\uffc7\011\uffc7\022" +
    "\uffc7\023\uffc7\024\uffc7\025\uffc7\026\uffc7\027\uffc7\030\uffc7" +
    "\031\uffc7\032\uffc7\041\uffc7\042\uffc7\043\uffc7\044\uffc7\045" +
    "\uffc7\046\uffc7\047\uffc7\050\uffc7\053\uffc7\054\uffc7\055\uffc7" +
    "\056\uffc7\061\uffc7\001\002\000\036\012\052\013\063\014" +
    "\053\023\016\024\027\025\020\027\042\051\046\052\050" +
    "\061\054\062\060\063\057\065\065\066\056\001\002\000" +
    "\072\002\uffcb\004\uffcb\005\uffcb\007\uffcb\010\uffcb\011\uffcb" +
    "\022\uffcb\023\uffcb\024\uffcb\025\uffcb\026\uffcb\027\uffcb\030" +
    "\103\031\102\032\101\041\uffcb\042\uffcb\043\uffcb\044\uffcb" +
    "\045\uffcb\046\uffcb\047\uffcb\050\uffcb\053\uffcb\054\uffcb\055" +
    "\uffcb\056\uffcb\061\uffcb\001\002\000\072\002\uffbf\004\uffbf" +
    "\005\uffbf\007\uffbf\010\uffbf\011\uffbf\022\uffbf\023\uffbf\024" +
    "\uffbf\025\uffbf\026\uffbf\027\uffbf\030\uffbf\031\uffbf\032\uffbf" +
    "\041\uffbf\042\uffbf\043\uffbf\044\uffbf\045\uffbf\046\uffbf\047" +
    "\uffbf\050\uffbf\053\uffbf\054\uffbf\055\uffbf\056\uffbf\061\uffbf" +
    "\001\002\000\072\002\uffbd\004\uffbd\005\uffbd\007\uffbd\010" +
    "\uffbd\011\uffbd\022\uffbd\023\uffbd\024\uffbd\025\uffbd\026\uffbd" +
    "\027\uffbd\030\uffbd\031\uffbd\032\uffbd\041\uffbd\042\uffbd\043" +
    "\uffbd\044\uffbd\045\uffbd\046\uffbd\047\uffbd\050\uffbd\053\uffbd" +
    "\054\uffbd\055\uffbd\056\uffbd\061\uffbd\001\002\000\072\002" +
    "\uffbc\004\uffbc\005\uffbc\007\uffbc\010\uffbc\011\uffbc\022\uffbc" +
    "\023\uffbc\024\uffbc\025\uffbc\026\uffbc\027\uffbc\030\uffbc\031" +
    "\uffbc\032\uffbc\041\uffbc\042\uffbc\043\uffbc\044\uffbc\045\uffbc" +
    "\046\uffbc\047\uffbc\050\uffbc\053\uffbc\054\uffbc\055\uffbc\056" +
    "\uffbc\061\uffbc\001\002\000\044\002\uffd8\004\uffd8\005\uffd8" +
    "\007\uffd8\010\uffd8\011\uffd8\022\uffd8\023\uffd8\024\uffd8\025" +
    "\uffd8\047\114\050\uffd8\053\uffd8\054\uffd8\055\uffd8\056\uffd8" +
    "\061\uffd8\001\002\000\072\002\uffc2\004\uffc2\005\uffc2\007" +
    "\uffc2\010\uffc2\011\uffc2\022\uffc2\023\uffc2\024\uffc2\025\uffc2" +
    "\026\uffc2\027\uffc2\030\uffc2\031\uffc2\032\uffc2\041\uffc2\042" +
    "\uffc2\043\uffc2\044\uffc2\045\uffc2\046\uffc2\047\uffc2\050\uffc2" +
    "\053\uffc2\054\uffc2\055\uffc2\056\uffc2\061\uffc2\001\002\000" +
    "\072\002\uffc0\004\uffc0\005\uffc0\007\uffc0\010\uffc0\011\uffc0" +
    "\022\uffc0\023\uffc0\024\uffc0\025\uffc0\026\uffc0\027\uffc0\030" +
    "\uffc0\031\uffc0\032\uffc0\041\uffc0\042\uffc0\043\uffc0\044\uffc0" +
    "\045\uffc0\046\uffc0\047\uffc0\050\uffc0\053\uffc0\054\uffc0\055" +
    "\uffc0\056\uffc0\061\uffc0\001\002\000\072\002\uffc1\004\uffc1" +
    "\005\uffc1\007\uffc1\010\uffc1\011\uffc1\022\uffc1\023\uffc1\024" +
    "\uffc1\025\uffc1\026\uffc1\027\uffc1\030\uffc1\031\uffc1\032\uffc1" +
    "\041\uffc1\042\uffc1\043\uffc1\044\uffc1\045\uffc1\046\uffc1\047" +
    "\uffc1\050\uffc1\053\uffc1\054\uffc1\055\uffc1\056\uffc1\061\uffc1" +
    "\001\002\000\060\002\uffd3\004\uffd3\005\uffd3\007\uffd3\010" +
    "\uffd3\011\uffd3\022\uffd3\023\uffd3\024\uffd3\025\uffd3\041\uffd3" +
    "\042\uffd3\043\073\044\074\045\072\046\071\047\uffd3\050" +
    "\uffd3\053\uffd3\054\uffd3\055\uffd3\056\uffd3\061\uffd3\001\002" +
    "\000\072\002\uffba\004\uffba\005\uffba\007\uffba\010\uffba\011" +
    "\uffba\022\uffba\023\uffba\024\uffba\025\uffba\026\uffba\027\uffba" +
    "\030\uffba\031\uffba\032\uffba\041\uffba\042\uffba\043\uffba\044" +
    "\uffba\045\uffba\046\uffba\047\uffba\050\uffba\053\uffba\054\uffba" +
    "\055\uffba\056\uffba\061\uffba\001\002\000\072\002\uffbe\004" +
    "\uffbe\005\uffbe\007\uffbe\010\uffbe\011\uffbe\022\uffbe\023\uffbe" +
    "\024\uffbe\025\uffbe\026\uffbe\027\uffbe\030\uffbe\031\uffbe\032" +
    "\uffbe\041\uffbe\042\uffbe\043\uffbe\044\uffbe\045\uffbe\046\uffbe" +
    "\047\uffbe\050\uffbe\053\uffbe\054\uffbe\055\uffbe\056\uffbe\061" +
    "\uffbe\001\002\000\050\002\uffd6\004\uffd6\005\uffd6\007\uffd6" +
    "\010\uffd6\011\uffd6\022\uffd6\023\uffd6\024\uffd6\025\uffd6\041" +
    "\066\042\067\047\uffd6\050\uffd6\053\uffd6\054\uffd6\055\uffd6" +
    "\056\uffd6\061\uffd6\001\002\000\072\002\uffc3\004\uffc3\005" +
    "\uffc3\007\uffc3\010\uffc3\011\uffc3\022\uffc3\023\uffc3\024\uffc3" +
    "\025\uffc3\026\uffc3\027\uffc3\030\uffc3\031\uffc3\032\uffc3\041" +
    "\uffc3\042\uffc3\043\uffc3\044\uffc3\045\uffc3\046\uffc3\047\uffc3" +
    "\050\uffc3\053\uffc3\054\uffc3\055\uffc3\056\uffc3\061\uffc3\001" +
    "\002\000\036\012\052\013\063\014\053\023\016\024\027" +
    "\025\020\027\042\051\046\052\050\061\054\062\060\063" +
    "\057\065\065\066\056\001\002\000\036\012\052\013\063" +
    "\014\053\023\016\024\027\025\020\027\042\051\046\052" +
    "\050\061\054\062\060\063\057\065\065\066\056\001\002" +
    "\000\060\002\uffd4\004\uffd4\005\uffd4\007\uffd4\010\uffd4\011" +
    "\uffd4\022\uffd4\023\uffd4\024\uffd4\025\uffd4\041\uffd4\042\uffd4" +
    "\043\073\044\074\045\072\046\071\047\uffd4\050\uffd4\053" +
    "\uffd4\054\uffd4\055\uffd4\056\uffd4\061\uffd4\001\002\000\036" +
    "\012\052\013\063\014\053\023\016\024\027\025\020\027" +
    "\042\051\046\052\050\061\054\062\060\063\057\065\065" +
    "\066\056\001\002\000\036\012\052\013\063\014\053\023" +
    "\016\024\027\025\020\027\042\051\046\052\050\061\054" +
    "\062\060\063\057\065\065\066\056\001\002\000\036\012" +
    "\052\013\063\014\053\023\016\024\027\025\020\027\042" +
    "\051\046\052\050\061\054\062\060\063\057\065\065\066" +
    "\056\001\002\000\036\012\052\013\063\014\053\023\016" +
    "\024\027\025\020\027\042\051\046\052\050\061\054\062" +
    "\060\063\057\065\065\066\056\001\002\000\064\002\uffd1" +
    "\004\uffd1\005\uffd1\007\uffd1\010\uffd1\011\uffd1\022\uffd1\023" +
    "\uffd1\024\uffd1\025\uffd1\026\076\027\077\041\uffd1\042\uffd1" +
    "\043\uffd1\044\uffd1\045\uffd1\046\uffd1\047\uffd1\050\uffd1\053" +
    "\uffd1\054\uffd1\055\uffd1\056\uffd1\061\uffd1\001\002\000\036" +
    "\012\052\013\063\014\053\023\016\024\027\025\020\027" +
    "\042\051\046\052\050\061\054\062\060\063\057\065\065" +
    "\066\056\001\002\000\036\012\052\013\063\014\053\023" +
    "\016\024\027\025\020\027\042\051\046\052\050\061\054" +
    "\062\060\063\057\065\065\066\056\001\002\000\072\002" +
    "\uffcc\004\uffcc\005\uffcc\007\uffcc\010\uffcc\011\uffcc\022\uffcc" +
    "\023\uffcc\024\uffcc\025\uffcc\026\uffcc\027\uffcc\030\103\031" +
    "\102\032\101\041\uffcc\042\uffcc\043\uffcc\044\uffcc\045\uffcc" +
    "\046\uffcc\047\uffcc\050\uffcc\053\uffcc\054\uffcc\055\uffcc\056" +
    "\uffcc\061\uffcc\001\002\000\036\012\052\013\063\014\053" +
    "\023\016\024\027\025\020\027\042\051\046\052\050\061" +
    "\054\062\060\063\057\065\065\066\056\001\002\000\036" +
    "\012\052\013\063\014\053\023\016\024\027\025\020\027" +
    "\042\051\046\052\050\061\054\062\060\063\057\065\065" +
    "\066\056\001\002\000\036\012\052\013\063\014\053\023" +
    "\016\024\027\025\020\027\042\051\046\052\050\061\054" +
    "\062\060\063\057\065\065\066\056\001\002\000\072\002" +
    "\uffca\004\uffca\005\uffca\007\uffca\010\uffca\011\uffca\022\uffca" +
    "\023\uffca\024\uffca\025\uffca\026\uffca\027\uffca\030\uffca\031" +
    "\uffca\032\uffca\041\uffca\042\uffca\043\uffca\044\uffca\045\uffca" +
    "\046\uffca\047\uffca\050\uffca\053\uffca\054\uffca\055\uffca\056" +
    "\uffca\061\uffca\001\002\000\072\002\uffc9\004\uffc9\005\uffc9" +
    "\007\uffc9\010\uffc9\011\uffc9\022\uffc9\023\uffc9\024\uffc9\025" +
    "\uffc9\026\uffc9\027\uffc9\030\uffc9\031\uffc9\032\uffc9\041\uffc9" +
    "\042\uffc9\043\uffc9\044\uffc9\045\uffc9\046\uffc9\047\uffc9\050" +
    "\uffc9\053\uffc9\054\uffc9\055\uffc9\056\uffc9\061\uffc9\001\002" +
    "\000\072\002\uffc8\004\uffc8\005\uffc8\007\uffc8\010\uffc8\011" +
    "\uffc8\022\uffc8\023\uffc8\024\uffc8\025\uffc8\026\uffc8\027\uffc8" +
    "\030\uffc8\031\uffc8\032\uffc8\041\uffc8\042\uffc8\043\uffc8\044" +
    "\uffc8\045\uffc8\046\uffc8\047\uffc8\050\uffc8\053\uffc8\054\uffc8" +
    "\055\uffc8\056\uffc8\061\uffc8\001\002\000\072\002\uffcd\004" +
    "\uffcd\005\uffcd\007\uffcd\010\uffcd\011\uffcd\022\uffcd\023\uffcd" +
    "\024\uffcd\025\uffcd\026\uffcd\027\uffcd\030\103\031\102\032" +
    "\101\041\uffcd\042\uffcd\043\uffcd\044\uffcd\045\uffcd\046\uffcd" +
    "\047\uffcd\050\uffcd\053\uffcd\054\uffcd\055\uffcd\056\uffcd\061" +
    "\uffcd\001\002\000\064\002\uffd2\004\uffd2\005\uffd2\007\uffd2" +
    "\010\uffd2\011\uffd2\022\uffd2\023\uffd2\024\uffd2\025\uffd2\026" +
    "\076\027\077\041\uffd2\042\uffd2\043\uffd2\044\uffd2\045\uffd2" +
    "\046\uffd2\047\uffd2\050\uffd2\053\uffd2\054\uffd2\055\uffd2\056" +
    "\uffd2\061\uffd2\001\002\000\064\002\uffd0\004\uffd0\005\uffd0" +
    "\007\uffd0\010\uffd0\011\uffd0\022\uffd0\023\uffd0\024\uffd0\025" +
    "\uffd0\026\076\027\077\041\uffd0\042\uffd0\043\uffd0\044\uffd0" +
    "\045\uffd0\046\uffd0\047\uffd0\050\uffd0\053\uffd0\054\uffd0\055" +
    "\uffd0\056\uffd0\061\uffd0\001\002\000\064\002\uffcf\004\uffcf" +
    "\005\uffcf\007\uffcf\010\uffcf\011\uffcf\022\uffcf\023\uffcf\024" +
    "\uffcf\025\uffcf\026\076\027\077\041\uffcf\042\uffcf\043\uffcf" +
    "\044\uffcf\045\uffcf\046\uffcf\047\uffcf\050\uffcf\053\uffcf\054" +
    "\uffcf\055\uffcf\056\uffcf\061\uffcf\001\002\000\060\002\uffd5" +
    "\004\uffd5\005\uffd5\007\uffd5\010\uffd5\011\uffd5\022\uffd5\023" +
    "\uffd5\024\uffd5\025\uffd5\041\uffd5\042\uffd5\043\073\044\074" +
    "\045\072\046\071\047\uffd5\050\uffd5\053\uffd5\054\uffd5\055" +
    "\uffd5\056\uffd5\061\uffd5\001\002\000\036\012\052\013\063" +
    "\014\053\023\016\024\027\025\020\027\042\051\046\052" +
    "\050\061\054\062\060\063\057\065\065\066\056\001\002" +
    "\000\050\002\uffd7\004\uffd7\005\uffd7\007\uffd7\010\uffd7\011" +
    "\uffd7\022\uffd7\023\uffd7\024\uffd7\025\uffd7\041\066\042\067" +
    "\047\uffd7\050\uffd7\053\uffd7\054\uffd7\055\uffd7\056\uffd7\061" +
    "\uffd7\001\002\000\004\053\117\001\002\000\072\002\uffbb" +
    "\004\uffbb\005\uffbb\007\uffbb\010\uffbb\011\uffbb\022\uffbb\023" +
    "\uffbb\024\uffbb\025\uffbb\026\uffbb\027\uffbb\030\uffbb\031\uffbb" +
    "\032\uffbb\041\uffbb\042\uffbb\043\uffbb\044\uffbb\045\uffbb\046" +
    "\uffbb\047\uffbb\050\uffbb\053\uffbb\054\uffbb\055\uffbb\056\uffbb" +
    "\061\uffbb\001\002\000\072\002\uffc5\004\uffc5\005\uffc5\007" +
    "\uffc5\010\uffc5\011\uffc5\022\uffc5\023\uffc5\024\uffc5\025\uffc5" +
    "\026\uffc5\027\uffc5\030\uffc5\031\uffc5\032\uffc5\041\uffc5\042" +
    "\uffc5\043\uffc5\044\uffc5\045\uffc5\046\uffc5\047\uffc5\050\uffc5" +
    "\053\uffc5\054\uffc5\055\uffc5\056\uffc5\061\uffc5\001\002\000" +
    "\036\012\052\013\063\014\053\023\016\024\027\025\020" +
    "\027\042\051\046\052\050\061\054\062\060\063\057\065" +
    "\065\066\056\001\002\000\044\002\uffd9\004\uffd9\005\uffd9" +
    "\007\uffd9\010\uffd9\011\uffd9\022\uffd9\023\uffd9\024\uffd9\025" +
    "\uffd9\047\114\050\uffd9\053\uffd9\054\uffd9\055\uffd9\056\uffd9" +
    "\061\uffd9\001\002\000\072\002\uffc6\004\uffc6\005\uffc6\007" +
    "\uffc6\010\uffc6\011\uffc6\022\uffc6\023\uffc6\024\uffc6\025\uffc6" +
    "\026\uffc6\027\uffc6\030\uffc6\031\uffc6\032\uffc6\041\uffc6\042" +
    "\uffc6\043\uffc6\044\uffc6\045\uffc6\046\uffc6\047\uffc6\050\uffc6" +
    "\053\uffc6\054\uffc6\055\uffc6\056\uffc6\061\uffc6\001\002\000" +
    "\036\012\052\013\063\014\053\023\016\024\027\025\020" +
    "\027\042\051\046\052\050\061\054\062\060\063\057\065" +
    "\065\066\056\001\002\000\004\053\126\001\002\000\074" +
    "\002\uffdf\004\uffdf\005\uffdf\007\uffdf\010\uffdf\011\uffdf\022" +
    "\uffdf\023\uffdf\024\uffdf\025\uffdf\026\uffdf\027\uffdf\030\uffdf" +
    "\031\uffdf\032\uffdf\041\uffdf\042\uffdf\043\uffdf\044\uffdf\045" +
    "\uffdf\046\uffdf\047\uffdf\050\uffdf\053\uffdf\054\uffdf\055\uffdf" +
    "\056\uffdf\057\uffdf\061\uffdf\001\002\000\004\054\015\001" +
    "\002\000\034\002\uffe3\004\uffe3\005\uffe3\007\uffe3\010\uffe3" +
    "\011\uffe3\022\uffe3\023\uffe3\024\uffe3\025\uffe3\054\uffe3\055" +
    "\uffe3\061\uffe3\001\002\000\034\002\ufff4\004\ufff4\005\ufff4" +
    "\007\ufff4\010\ufff4\011\ufff4\022\ufff4\023\ufff4\024\ufff4\025" +
    "\ufff4\054\ufff4\055\ufff4\061\ufff4\001\002\000\042\012\052" +
    "\013\063\014\053\023\016\024\027\025\020\027\042\051" +
    "\046\052\050\053\uffdb\056\uffdb\061\054\062\060\063\057" +
    "\065\065\066\056\001\002\000\006\053\uffdc\056\uffdc\001" +
    "\002\000\006\053\136\056\135\001\002\000\036\012\052" +
    "\013\063\014\053\023\016\024\027\025\020\027\042\051" +
    "\046\052\050\061\054\062\060\063\057\065\065\066\056" +
    "\001\002\000\036\002\uffe1\004\uffe1\005\uffe1\007\uffe1\010" +
    "\uffe1\011\uffe1\022\uffe1\023\uffe1\024\uffe1\025\uffe1\054\uffe1" +
    "\055\uffe1\057\137\061\uffe1\001\002\000\034\002\uffe2\004" +
    "\uffe2\005\uffe2\007\uffe2\010\uffe2\011\uffe2\022\uffe2\023\uffe2" +
    "\024\uffe2\025\uffe2\054\uffe2\055\uffe2\061\uffe2\001\002\000" +
    "\006\053\uffdd\056\uffdd\001\002\000\036\012\052\013\063" +
    "\014\053\023\016\024\027\025\020\027\042\051\046\052" +
    "\050\061\054\062\060\063\057\065\065\066\056\001\002" +
    "\000\004\053\143\001\002\000\074\002\uffde\004\uffde\005" +
    "\uffde\007\uffde\010\uffde\011\uffde\022\uffde\023\uffde\024\uffde" +
    "\025\uffde\026\uffde\027\uffde\030\uffde\031\uffde\032\uffde\041" +
    "\uffde\042\uffde\043\uffde\044\uffde\045\uffde\046\uffde\047\uffde" +
    "\050\uffde\053\uffde\054\uffde\055\uffde\056\uffde\057\uffde\061" +
    "\uffde\001\002\000\036\012\052\013\063\014\053\023\016" +
    "\024\027\025\020\027\042\051\046\052\050\061\054\062" +
    "\060\063\057\065\065\066\056\001\002\000\004\053\146" +
    "\001\002\000\074\002\uffe0\004\uffe0\005\uffe0\007\uffe0\010" +
    "\uffe0\011\uffe0\022\uffe0\023\uffe0\024\uffe0\025\uffe0\026\uffe0" +
    "\027\uffe0\030\uffe0\031\uffe0\032\uffe0\041\uffe0\042\uffe0\043" +
    "\uffe0\044\uffe0\045\uffe0\046\uffe0\047\uffe0\050\uffe0\053\uffe0" +
    "\054\uffe0\055\uffe0\056\uffe0\057\uffe0\061\uffe0\001\002\000" +
    "\032\004\030\005\010\007\026\010\024\011\004\022\022" +
    "\023\016\024\027\025\020\054\015\055\151\061\013\001" +
    "\002\000\034\002\uffff\004\uffff\005\uffff\007\uffff\010\uffff" +
    "\011\uffff\022\uffff\023\uffff\024\uffff\025\uffff\054\uffff\055" +
    "\uffff\061\uffff\001\002\000\036\002\ufffc\004\ufffc\005\ufffc" +
    "\006\ufffc\007\ufffc\010\ufffc\011\ufffc\022\ufffc\023\ufffc\024" +
    "\ufffc\025\ufffc\054\ufffc\055\ufffc\061\ufffc\001\002\000\004" +
    "\002\001\001\002\000\036\012\052\013\063\014\053\023" +
    "\016\024\027\025\020\027\042\051\046\052\050\061\054" +
    "\062\060\063\057\065\065\066\056\001\002\000\034\002" +
    "\ufff1\004\ufff1\005\ufff1\007\ufff1\010\ufff1\011\ufff1\022\ufff1" +
    "\023\ufff1\024\ufff1\025\ufff1\054\ufff1\055\ufff1\061\ufff1\001" +
    "\002\000\036\012\052\013\063\014\053\023\016\024\027" +
    "\025\020\027\042\051\046\052\050\061\054\062\060\063" +
    "\057\065\065\066\056\001\002\000\034\002\ufff2\004\ufff2" +
    "\005\ufff2\007\ufff2\010\ufff2\011\ufff2\022\ufff2\023\ufff2\024" +
    "\ufff2\025\ufff2\054\ufff2\055\ufff2\061\ufff2\001\002\000\036" +
    "\012\052\013\063\014\053\023\016\024\027\025\020\027" +
    "\042\051\046\052\050\061\054\062\060\063\057\065\065" +
    "\066\056\001\002\000\036\012\052\013\063\014\053\023" +
    "\016\024\027\025\020\027\042\051\046\052\050\061\054" +
    "\062\060\063\057\065\065\066\056\001\002\000\034\002" +
    "\uffeb\004\uffeb\005\uffeb\007\uffeb\010\uffeb\011\uffeb\022\uffeb" +
    "\023\uffeb\024\uffeb\025\uffeb\054\uffeb\055\uffeb\061\uffeb\001" +
    "\002\000\034\002\uffed\004\uffed\005\uffed\007\uffed\010\uffed" +
    "\011\uffed\022\uffed\023\uffed\024\uffed\025\uffed\054\uffed\055" +
    "\uffed\061\uffed\001\002\000\034\002\uffee\004\uffee\005\uffee" +
    "\007\uffee\010\uffee\011\uffee\022\uffee\023\uffee\024\uffee\025" +
    "\uffee\054\uffee\055\uffee\061\uffee\001\002\000\034\002\uffec" +
    "\004\uffec\005\uffec\007\uffec\010\uffec\011\uffec\022\uffec\023" +
    "\uffec\024\uffec\025\uffec\054\uffec\055\uffec\061\uffec\001\002" +
    "\000\004\054\015\001\002\000\036\002\uffe5\004\uffe5\005" +
    "\uffe5\006\167\007\uffe5\010\uffe5\011\uffe5\022\uffe5\023\uffe5" +
    "\024\uffe5\025\uffe5\054\uffe5\055\uffe5\061\uffe5\001\002\000" +
    "\004\054\015\001\002\000\034\002\uffe4\004\uffe4\005\uffe4" +
    "\007\uffe4\010\uffe4\011\uffe4\022\uffe4\023\uffe4\024\uffe4\025" +
    "\uffe4\054\uffe4\055\uffe4\061\uffe4\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\166\000\026\002\013\003\016\004\006\005\024\006" +
    "\011\007\005\010\020\022\010\023\022\025\004\001\001" +
    "\000\002\001\001\000\022\003\147\004\006\005\024\006" +
    "\011\007\005\010\020\022\010\023\022\001\001\000\002" +
    "\001\001\000\002\001\001\000\026\011\164\012\042\013" +
    "\054\014\063\015\060\016\040\017\050\020\046\021\044" +
    "\023\061\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\024\003\016\004\006" +
    "\005\024\006\011\007\005\010\020\022\010\023\022\025" +
    "\146\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\026\011\126" +
    "\012\042\013\054\014\063\015\060\016\040\017\050\020" +
    "\046\021\044\023\061\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\024\032\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\026\011\043\012\042\013" +
    "\054\014\063\015\060\016\040\017\050\020\046\021\044" +
    "\023\061\001\001\000\002\001\001\000\010\020\122\021" +
    "\044\023\061\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\020\117\021\044\023\061\001" +
    "\001\000\002\001\001\000\026\011\115\012\042\013\054" +
    "\014\063\015\060\016\040\017\050\020\046\021\044\023" +
    "\061\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\016\015\112\016\040\017\050\020\046" +
    "\021\044\023\061\001\001\000\016\015\067\016\040\017" +
    "\050\020\046\021\044\023\061\001\001\000\002\001\001" +
    "\000\014\016\111\017\050\020\046\021\044\023\061\001" +
    "\001\000\014\016\110\017\050\020\046\021\044\023\061" +
    "\001\001\000\014\016\107\017\050\020\046\021\044\023" +
    "\061\001\001\000\014\016\074\017\050\020\046\021\044" +
    "\023\061\001\001\000\002\001\001\000\012\017\106\020" +
    "\046\021\044\023\061\001\001\000\012\017\077\020\046" +
    "\021\044\023\061\001\001\000\002\001\001\000\010\020" +
    "\105\021\044\023\061\001\001\000\010\020\104\021\044" +
    "\023\061\001\001\000\010\020\103\021\044\023\061\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\020\014\114\015\060" +
    "\016\040\017\050\020\046\021\044\023\061\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\022\013\121\014\063\015\060\016\040\017" +
    "\050\020\046\021\044\023\061\001\001\000\002\001\001" +
    "\000\002\001\001\000\026\011\124\012\042\013\054\014" +
    "\063\015\060\016\040\017\050\020\046\021\044\023\061" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\004" +
    "\127\001\001\000\002\001\001\000\002\001\001\000\030" +
    "\011\132\012\042\013\054\014\063\015\060\016\040\017" +
    "\050\020\046\021\044\023\061\026\133\001\001\000\002" +
    "\001\001\000\002\001\001\000\026\011\137\012\042\013" +
    "\054\014\063\015\060\016\040\017\050\020\046\021\044" +
    "\023\061\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\026\011\141\012\042\013\054\014\063" +
    "\015\060\016\040\017\050\020\046\021\044\023\061\001" +
    "\001\000\002\001\001\000\002\001\001\000\026\011\144" +
    "\012\042\013\054\014\063\015\060\016\040\017\050\020" +
    "\046\021\044\023\061\001\001\000\002\001\001\000\002" +
    "\001\001\000\022\003\147\004\006\005\024\006\011\007" +
    "\005\010\020\022\010\023\022\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\026\011\163\012" +
    "\042\013\054\014\063\015\060\016\040\017\050\020\046" +
    "\021\044\023\061\001\001\000\002\001\001\000\026\011" +
    "\162\012\042\013\054\014\063\015\060\016\040\017\050" +
    "\020\046\021\044\023\061\001\001\000\002\001\001\000" +
    "\026\011\161\012\042\013\054\014\063\015\060\016\040" +
    "\017\050\020\046\021\044\023\061\001\001\000\026\011" +
    "\160\012\042\013\054\014\063\015\060\016\040\017\050" +
    "\020\046\021\044\023\061\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\004\165\001\001\000\002\001\001\000\004\004\167\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void syntax_error(Symbol s){
        System.out.println(
            "Error sintáctico en línea "
            + s.left +
            ", columna "
            + s.right
        );
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Nodo start_val = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= lista_sentencias 
            {
              Nodo RESULT =null;
		int lsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ArrayList ls = (ArrayList)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = new Nodo("programa", ls);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // lista_sentencias ::= lista_sentencias sentencia 
            {
              ArrayList RESULT =null;
		int lsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList ls = (ArrayList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo s = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        ls.add(s);
        RESULT = ls;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // lista_sentencias ::= sentencia 
            {
              ArrayList RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo s = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        ArrayList lista = new ArrayList();
        lista.add(s);
        RESULT = lista;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // lista_sentencias ::= 
            {
              ArrayList RESULT =null;
		
        RESULT = new ArrayList();
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // bloque ::= LLAVEIZQ lista_sentencias LLAVEDER 
            {
              Nodo RESULT =null;
		int lsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList ls = (ArrayList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        RESULT = new Nodo("bloque", ls);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // sentencia ::= declaracion_var 
            {
              Nodo RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo d = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = d; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // sentencia ::= asignacion 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = a; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // sentencia ::= sentencia_if 
            {
              Nodo RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo i = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = i; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // sentencia ::= sentencia_for 
            {
              Nodo RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo f = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = f; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // sentencia ::= BREAK 
            {
              Nodo RESULT =null;
		
        RESULT = new Nodo("break", (Object)null);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // sentencia ::= CONTINUE 
            {
              Nodo RESULT =null;
		
        RESULT = new Nodo("continue", (Object)null);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // sentencia ::= println_stmt 
            {
              Nodo RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo p = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = p; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // sentencia ::= llamada_funcion PUNTOCOMA 
            {
              Nodo RESULT =null;
		int lfleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lfright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Nodo lf = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = lf; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // sentencia ::= bloque 
            {
              Nodo RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo b = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = b; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // sentencia ::= ID MASMAS 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        RESULT = new Nodo("incremento", id);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // sentencia ::= ID MENOSMENOS 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        RESULT = new Nodo("decremento", id);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // declaracion_var ::= VAR ID tipo IGUAL expresion 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Nodo t = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = new Nodo("var_decl", id, t, e);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracion_var",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // declaracion_var ::= VAR ID tipo 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo t = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = new Nodo("var_decl_sin_valor", id, t);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracion_var",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // declaracion_var ::= ID DOSPUNTOIGUAL expresion 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = new Nodo("var_inferida", id, e);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracion_var",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // asignacion ::= ID IGUAL expresion 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = new Nodo("asignacion", id, e);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("asignacion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // asignacion ::= ID MASIGUAL expresion 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = new Nodo("mas_igual", id, e);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("asignacion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // asignacion ::= ID MENOSIGUAL expresion 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = new Nodo("menos_igual", id, e);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("asignacion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // tipo ::= TINT 
            {
              Nodo RESULT =null;
		 RESULT = new Nodo("tipo", "int"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // tipo ::= TFLOAT 
            {
              Nodo RESULT =null;
		 RESULT = new Nodo("tipo", "float64"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // tipo ::= TSTRING 
            {
              Nodo RESULT =null;
		 RESULT = new Nodo("tipo", "string"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // tipo ::= TBOOL 
            {
              Nodo RESULT =null;
		 RESULT = new Nodo("tipo", "bool"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // tipo ::= TRUNE 
            {
              Nodo RESULT =null;
		 RESULT = new Nodo("tipo", "rune"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // sentencia_if ::= IF expresion bloque 
            {
              Nodo RESULT =null;
		int condleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Nodo cond = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo b = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = new Nodo("if", cond, b);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_if",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // sentencia_if ::= IF expresion bloque ELSE bloque 
            {
              Nodo RESULT =null;
		int condleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Nodo cond = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Nodo b = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = new Nodo("if_else", cond, b, e);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_if",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // sentencia_for ::= FOR expresion bloque 
            {
              Nodo RESULT =null;
		int condleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Nodo cond = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo b = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = new Nodo("for_while", cond, b);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia_for",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // println_stmt ::= PRINTLN PARIZQ lista_args PARDER PUNTOCOMA 
            {
              Nodo RESULT =null;
		int argsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int argsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		ArrayList args = (ArrayList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		
        RESULT = new Nodo("println", args);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("println_stmt",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // println_stmt ::= PRINTLN PARIZQ lista_args PARDER 
            {
              Nodo RESULT =null;
		int argsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int argsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList args = (ArrayList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        RESULT = new Nodo("println", args);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("println_stmt",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // llamada_funcion ::= ATOI PARIZQ expresion PARDER 
            {
              Nodo RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        RESULT = new Nodo("atoi", e);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("llamada_funcion",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // llamada_funcion ::= PARSEFLOAT PARIZQ expresion PARDER 
            {
              Nodo RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        RESULT = new Nodo("parsefloat", e);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("llamada_funcion",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // llamada_funcion ::= TYPEOF PARIZQ expresion PARDER 
            {
              Nodo RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
        RESULT = new Nodo("typeof", e);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("llamada_funcion",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // lista_args ::= lista_args COMA expresion 
            {
              ArrayList RESULT =null;
		int laleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int laright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		ArrayList la = (ArrayList)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        la.add(e);
        RESULT = la;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_args",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // lista_args ::= expresion 
            {
              ArrayList RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        ArrayList lista = new ArrayList();
        lista.add(e);
        RESULT = lista;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_args",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // lista_args ::= 
            {
              ArrayList RESULT =null;
		
        RESULT = new ArrayList();
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_args",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expresion ::= expresion_or 
            {
              Nodo RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expresion_or ::= expresion_or OR expresion_and 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo b = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Nodo("or", a, b); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_or",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // expresion_or ::= expresion_and 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = a; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_or",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expresion_and ::= expresion_and AND expresion_eq 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo b = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Nodo("and", a, b); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_and",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expresion_and ::= expresion_eq 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = a; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_and",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expresion_eq ::= expresion_eq IGUALIGUAL expresion_rel 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo b = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Nodo("==", a, b); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_eq",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expresion_eq ::= expresion_eq DIFERENTE expresion_rel 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo b = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Nodo("!=", a, b); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_eq",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expresion_eq ::= expresion_rel 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = a; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_eq",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expresion_rel ::= expresion_rel MENOR expresion_add 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo b = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Nodo("<", a, b); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_rel",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expresion_rel ::= expresion_rel MAYOR expresion_add 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo b = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Nodo(">", a, b); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_rel",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expresion_rel ::= expresion_rel MENORIGUAL expresion_add 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo b = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Nodo("<=", a, b); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_rel",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expresion_rel ::= expresion_rel MAYORIGUAL expresion_add 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo b = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Nodo(">=", a, b); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_rel",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expresion_rel ::= expresion_add 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = a; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_rel",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expresion_add ::= expresion_add MAS expresion_mul 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo b = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Nodo("+", a, b); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_add",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expresion_add ::= expresion_add MENOS expresion_mul 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo b = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Nodo("-", a, b); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_add",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expresion_add ::= expresion_mul 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = a; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_add",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expresion_mul ::= expresion_mul POR expresion_unaria 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo b = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Nodo("*", a, b); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_mul",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expresion_mul ::= expresion_mul DIV expresion_unaria 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo b = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Nodo("/", a, b); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_mul",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expresion_mul ::= expresion_mul MOD expresion_unaria 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo b = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Nodo("%", a, b); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_mul",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expresion_mul ::= expresion_unaria 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = a; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_mul",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expresion_unaria ::= MENOS expresion_unaria 
            {
              Nodo RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = new Nodo("negacion", e);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_unaria",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expresion_unaria ::= NOT expresion_unaria 
            {
              Nodo RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = new Nodo("not", e);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_unaria",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expresion_unaria ::= expresion_primaria 
            {
              Nodo RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo a = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        RESULT = a;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_unaria",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expresion_primaria ::= LITINT 
            {
              Nodo RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Nodo("entero", n); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_primaria",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expresion_primaria ::= LITFLOAT 
            {
              Nodo RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Double f = (Double)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Nodo("decimal", f); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_primaria",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expresion_primaria ::= LITSTRING 
            {
              Nodo RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Nodo("cadena", s); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_primaria",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expresion_primaria ::= LITRUNE 
            {
              Nodo RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String r = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Nodo("rune", r); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_primaria",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expresion_primaria ::= TRUE 
            {
              Nodo RESULT =null;
		 RESULT = new Nodo("booleano", true); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_primaria",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // expresion_primaria ::= FALSE 
            {
              Nodo RESULT =null;
		 RESULT = new Nodo("booleano", false); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_primaria",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // expresion_primaria ::= NIL 
            {
              Nodo RESULT =null;
		 RESULT = new Nodo("nil", (Object)null); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_primaria",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // expresion_primaria ::= ID 
            {
              Nodo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Nodo("id", id); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_primaria",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // expresion_primaria ::= PARIZQ expresion PARDER 
            {
              Nodo RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Nodo e = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_primaria",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // expresion_primaria ::= llamada_funcion 
            {
              Nodo RESULT =null;
		int lfleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lfright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Nodo lf = (Nodo)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = lf; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_primaria",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
