
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package golite.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MASMAS = 29;
  public static final int TSTRING = 13;
  public static final int MENOSMENOS = 30;
  public static final int POR = 22;
  public static final int TFLOAT = 12;
  public static final int LITSTRING = 48;
  public static final int DIFERENTE = 32;
  public static final int CONTINUE = 7;
  public static final int LLAVEDER = 43;
  public static final int PUNTOCOMA = 45;
  public static final int PRINTLN = 16;
  public static final int FOR = 5;
  public static final int LITFLOAT = 52;
  public static final int NOT = 39;
  public static final int AND = 37;
  public static final int MENORIGUAL = 35;
  public static final int IGUAL = 25;
  public static final int PARSEFLOAT = 18;
  public static final int TYPEOF = 19;
  public static final int MASIGUAL = 27;
  public static final int NIL = 10;
  public static final int OR = 38;
  public static final int TBOOL = 14;
  public static final int DIV = 23;
  public static final int ATOI = 17;
  public static final int IF = 3;
  public static final int ID = 47;
  public static final int MAYORIGUAL = 36;
  public static final int PARIZQ = 40;
  public static final int EOF = 0;
  public static final int LITRUNE = 49;
  public static final int TRUE = 8;
  public static final int error = 1;
  public static final int COMA = 44;
  public static final int MENOS = 21;
  public static final int MENOR = 33;
  public static final int MOD = 24;
  public static final int BREAK = 6;
  public static final int ERROR = 50;
  public static final int TRUNE = 15;
  public static final int MAYOR = 34;
  public static final int TINT = 11;
  public static final int DOSPUNTOIGUAL = 26;
  public static final int ELSE = 4;
  public static final int PUNTO = 46;
  public static final int IGUALIGUAL = 31;
  public static final int LLAVEIZQ = 42;
  public static final int MENOSIGUAL = 28;
  public static final int PARDER = 41;
  public static final int FALSE = 9;
  public static final int LITINT = 51;
  public static final int VAR = 2;
  public static final int MAS = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VAR",
  "IF",
  "ELSE",
  "FOR",
  "BREAK",
  "CONTINUE",
  "TRUE",
  "FALSE",
  "NIL",
  "TINT",
  "TFLOAT",
  "TSTRING",
  "TBOOL",
  "TRUNE",
  "PRINTLN",
  "ATOI",
  "PARSEFLOAT",
  "TYPEOF",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "MOD",
  "IGUAL",
  "DOSPUNTOIGUAL",
  "MASIGUAL",
  "MENOSIGUAL",
  "MASMAS",
  "MENOSMENOS",
  "IGUALIGUAL",
  "DIFERENTE",
  "MENOR",
  "MAYOR",
  "MENORIGUAL",
  "MAYORIGUAL",
  "AND",
  "OR",
  "NOT",
  "PARIZQ",
  "PARDER",
  "LLAVEIZQ",
  "LLAVEDER",
  "COMA",
  "PUNTOCOMA",
  "PUNTO",
  "ID",
  "LITSTRING",
  "LITRUNE",
  "ERROR",
  "LITINT",
  "LITFLOAT"
  };
}

